# Generated by Django 4.1.5 on 2023-01-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Used_clothes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='goals',
            field=models.TextField(),
        ),
    ]
