# Generated by Django 4.1.5 on 2023-01-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Used_clothes_app', '0002_alter_institution_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Used_clothes_app.category'),
        ),
    ]
