# Generated by Django 4.1.5 on 2023-01-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Used_clothes_app', '0003_alter_donation_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
