# Generated by Django 4.1.5 on 2023-01-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Used_clothes_app', '0004_alter_donation_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
